### PR TITLE
feat: add playwright code coverage

### PR DESCRIPTION
**Pull request by SgtPooki**
Related to https://github.com/ipfs/ipfs-webui/issues/1965 in order to see where the riskier dependency updates are

### CODE REVIEW

**Review by hacdias — COMMENTED** [review]
The changes look fine, but I'm trying to understand how we can see the report. I took a look at the logs, but it doesn't say much:

image

**Comment by SgtPooki** [comment]
> The changes look fine, but I'm trying to understand how we can see the report. I took a look at the logs, but it doesn't say much:
> 
> image

For now, the reports are just going to be available manually, until we can integrate with codecov with https://github.com/codecov/codecov-action#usage.

It looks like js-test-and-releast.yml which is part of Unified CI JS uses codecov: https://github.com/search?q=org%3Aipfs+codecov%2Fcodecov-action&type=code

**Comment by SgtPooki** [comment]
Created https://github.com/ipfs/ipfs-webui/issues/2016 to track the next tasks

**Comment by SgtPooki** [comment]
@hacdias @lidel partially solved #2016 by adding codecov action, and you can see that the stats posted correctly at https://app.codecov.io/gh/ipfs/ipfs-webui/pull/2014 

Merging this PR

**Pull request merged**
