### PR TITLE
feat: IPNS Publishing

### LINKED ISSUE #1482: Support for publishing to IPNS
**Is your feature request related to a problem? Please describe.**
It's annoying to have to use the terminal to publish content to an IPNS key, and it alienates non-powerusers.

**Describe the solution you'd like**
It would be nice if the webui let you generate, organize, and name IPNS keys that files and folders could then be published to via the dropdown menu.

### PR DESCRIPTION
**Pull request by hacdias**
Please see PR #1857 for what happened and background on this. Closes #1482.

### Generate New Key

image

### Publishing Keys Settings Menu

image

### Drop Down

image

### Publish

image

image

image

### CODE REVIEW

**Comment by hacdias** [comment]
@lidel so something [happened](https://github.com/ipfs/ipfs-webui/pull/1857#issuecomment-1179668820) with the other PR and I had to create this new one. The E2E tests seem to be failing. I tried the functionality and everything seems to work as expected. Could you take a look at the tests since you were the last working on them (as far as I remember)?

**Comment by SgtPooki** [comment]
> @lidel so something [happened](https://github.com/ipfs/ipfs-webui/pull/1857#issuecomment-1179668820) with the other PR and I had to create this new one. The E2E tests seem to be failing. I tried the functionality and everything seems to work as expected. Could you take a look at the tests since you were the last working on them (as far as I remember)?

One thing that has broken e2e tests time and time again for me is modifying the package-lock and/or package.json with a different version of node. Be sure you're using node=16.12.0 and npm=8.1.0 and then do:

```bash
git checkout origin/main -- package-lock.json
```

**Comment by SgtPooki** [comment]
@hacdias 
> > @lidel so something [happened](https://github.com/ipfs/ipfs-webui/pull/1857#issuecomment-1179668820) with the other PR and I had to create this new one. The E2E tests seem to be failing. I tried the functionality and everything seems to work as expected. Could you take a look at the tests since you were the last working on them (as far as I remember)?
> 
> One thing that has broken e2e tests time and time again for me is modifying the package-lock and/or package.json with a different version of node. Be sure you're using node=16.12.0 and npm=8.1.0 and then do:
> 
> ```shell
> git checkout origin/main -- package-lock.json
> ```

**Comment by hacdias** [comment]
@SgtPooki I did that, but there's dependency updates so it changed a bit. Yet, the E2E tests keep failing with:

```
Requiring @playwright/test second time
```

I know @lidel worked on the tests of this PR, so it'd be great to get some feedback here!

**Comment by lidel** [comment]
I finished migration to @playwright/test in #1983, will merge into this PR shortly.  :crossed_fingers:

**Review by lidel — APPROVED** [review]
Fixed E2E tests, overall lgtm, thank you @hacdias for your patience here :heart: 

My hope was to have ipns over pubsub enabled everywhere when we merge this,
but I think having it in Desktop is good enough, and things may improve further 
when we have delegated IPNS publishing over Reframe.

Let's wait for :+1:  from a native speaker / UX folks till the end of this week, 
and then merge.

**Review by juliaxbow — COMMENTED** [review]
Alternative text suggestions: 

**Generate new IPNS Key**
- **Previous text:** Enter pet name of key to create.
- **New text:** Enter a nickname for this key to generate:
- **Description of change:** nickname instead of pet name

**Drop Down**
- I prefer capitalizing the first letter of each word for dropdowns but not necessary

**Publish**
- **Previous text:** Please wait while initial 20 copies of the updated IPNS record are being stored with the help of DHT peers.
- **New Text:** Please wait while the initial 20 copies of the updated IPNS record are stored with the help of DHT peers.
- **Description of change:** verb tense

- **Previous Text:** Copy the link below and share it with your friends. IPNS address will resolve as long as your node remains available on the network to refresh IPNS record once a day.
- **New text:** Copy the link below and share it with your friends. The IPNS address will resolve as long as your node remains available on the network once a day to refresh the IPNS record. 
- **Description of change:** Added “The” before “IPNS address” ; moved "once a day" to middle of the sentence
- **Question**: is sharing with friends the most common use case? Consider replacing “your friends” with “others” or "your network"

**Comment by TheDiscordian** [comment]
Just some minor alterations to the text:

"Enter pet name of key to create." -> "Enter a name for the new key."

"Please wait while initial 20 copies of the updated IPNS record are being stored with the help of DHT peers..." -> "Please wait while an initial 20 copies of the updated IPNS record are being stored with the help of DHT peers..."

"IPNS address will resolve as long your node remains available on the network to refresh IPNS record once a day." -> "The IPNS address will resolve as long as your node remains available on the network to refresh the IPNS record once a day."

Thanks for this work, very excited to have this feature in the webUI ^-^.

**Comment by hacdias** [comment]
@lidel I updated the copy based on @juliaxbow's and @TheDiscordian's suggestions.

**Comment by lidel** [comment]
Thank you! Merging so these new labels land in `main` branch and our translation teams have more time to translate before we cut a new release (~next week?) for Kubo 0.15.

Side notes:
- context menu is getting crowded
- feel we could improve presentation of key names and CIDs (right now it is bland monospace font), 
  but that requires some additional UX work – I will fill a new issue for it.

**Pull request merged**
