### PR TITLE
chore: update storybook and stories

### LINKED ISSUE #1982: chore: Update storybook
From http://localhost:9009/?path=/settings/about:

Upgrade all Storybook packages to latest:
```
npx npm-check-updates '/storybook/' -u && npm install
```
Alternatively, if you're using yarn run the following command, and check all Storybook related packages:
```
yarn upgrade-interactive --latest
```

### To do
- [x] https://github.com/storybookjs/storybook/blob/v6.5.9/MIGRATION.md#from-version-53x-to-60x
- [x] https://github.com/storybookjs/storybook/blob/v6.5.9/MIGRATION.md#from-version-60x-to-610
- [x] https://github.com/storybookjs/storybook/blob/v6.5.9/MIGRATION.md#from-version-61x-to-620
- [x] https://github.com/storybookjs/storybook/blob/v6.5.9/MIGRATION.md#from-version-62x-to-630
- [x] https://github.com/storybookjs/storybook/blob/v6.5.9/MIGRATION.md#from-version-63x-to-640
- [x] https://github.com/storybookjs/storybook/blob/v6.5.9/MIGRATION.md#from-version-64x-to-650

### Fixes
* https://github.com/ipfs/ipfs-webui/security/dependabot/92
* https://github.com/ipfs/ipfs-webui/security/dependabot/41

### Partially fixes
* https://github.com/ipfs/ipfs-webui/security/dependabot/87

### PR DESCRIPTION
**Pull request by SgtPooki**
Upgrades storybook and all storybook stories

fixes #1982

### CODE REVIEW

**Comment by hacdias** [comment]
@SgtPooki I cannot run the storybook. I get the following error:

```
Error: CSF: unexpected storiesOf call /Users/hacdias/Code/ipfs/ipfs-webui/src/components/radio/Radio.stories.js (line 12, col 0)
```

Found this issue (https://github.com/storybookjs/storybook/issues/18640) but no more information.

I tried different node versions (16.12.0 and 16.15.0), as well as npm install and npm ci. Did you encounter this error too?

**Comment by SgtPooki** [comment]
> @SgtPooki I cannot run the storybook. I get the following error:
> 
> ```
> Error: CSF: unexpected storiesOf call /Users/hacdias/Code/ipfs/ipfs-webui/src/components/radio/Radio.stories.js (line 12, col 0)
> ```
> 
> Found this issue ([storybookjs/storybook#18640](https://github.com/storybookjs/storybook/issues/18640)) but no more information.
> 
> I tried different node versions (16.12.0 and 16.15.0), as well as npm install and npm ci. Did you encounter this error too?

There should be no more `storiesOf` calls. I thought I got rid of all of them.. I will look into it

**Comment by SgtPooki** [comment]
Looks like there are some remaining storiesOf that must have stuck around after merging from main or something.

```bash
╰─ ✔ ❯ git status && rg 'storiesOf' .

On branch 1982-chore-update-storybook
Your branch is up to date with 'origin/1982-chore-update-storybook'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	.cache/
	.nyc_output/
	install-missing-deps.md
	npm-install
	pnpm-import.log
	pnpm-lock.yaml
	test-repos.sh

nothing added to commit but untracked files present (use "git add" to track)
./src/components/radio/Radio.stories.js
2:import { storiesOf } from '@storybook/react'
12:storiesOf('Radio', module)

./src/files/modals/publish-modal/PublishModal.stories.js
2:import { storiesOf } from '@storybook/react'
7:storiesOf('Files/Modals', module)
```

**Review by hacdias — APPROVED** [review]
Looks good to me. I checked both the code and the storybook itself.

**Pull request merged**
