### PR TITLE
feat: add 4EVERLAND to list of pinning service providers

### PR DESCRIPTION
**Pull request by cachalots**
[4EVERLNAD IPFS Pinning Service API docs](https://docs.4everland.org/storage/4ever-pin/pinning-services-api)
https://github.com/ipfs-shipyard/pinning-service-compliance/pull/287

### CODE REVIEW

**Comment by SgtPooki** [comment]
Currently blocked by https://github.com/ipfs-shipyard/pinning-service-compliance/pull/287

**Comment by cachalots** [comment]
> Currently blocked by [ipfs-shipyard/pinning-service-compliance#287](https://github.com/ipfs-shipyard/pinning-service-compliance/pull/287)

We have already cleared the obstacles, please continue.

**Comment by cachalots** [comment]
@SgtPooki https://github.com/ipfs-shipyard/pinning-service-compliance/pull/301 Has been merged! Let's push forward the merger of this PR.

**Comment by cachalots** [comment]
@SgtPooki Hello, are there any other issues that need to be addressed in this PR?

**Comment by SgtPooki** [comment]
@cachalots sorry for the delay! I'm going to look at this now!

**Review by SgtPooki — APPROVED** [review]
LGTM

**Pull request merged**
