### PR TITLE
feat: ux improvements to publish modal

### LINKED ISSUE #1993: Improve UX of IPNS publishing
Now that we've added basic UI for publishing CIDs to IPNS (#1973) :partying_face: 
it may be a good time to go an extra mile and refine the UI.

Namely, I feel we could improve presentation of key names and CIDs (right now it is a bland monospace font).
Perhaps we could also add one-line explainer to the first modal (imagine user clicking "Publish to IPNS" and not knowing what it is):

Below is the current state:  

| Before Publishing |  Published | 
| ---- | ---- |
|   |  |

any ideas are welcome, cc @juliaxbow @hacdias

### PR DESCRIPTION
**Pull request by hacdias**
Closes #1993

When it finishes publishing:

image

After clicking:

image

Then the icon goes back to normal after 2 seconds.

### CODE REVIEW

**Comment by lidel** [comment]
cc @juliaxbow for :eyes:

**Comment by juliaxbow** [comment]
Minor changes to the success state after clicking the copy icon: 
- Icon: padding to the right of the success icon should be increased by 3px to match copy icon formatting
- Link field: opacity of text or fill of #ffffff at 60% opacity should occur alongside the success message so that it is more legible
- Success message: I think the tone of "Link copied!" over "Link copied" fits better
Screen Shot 2022-08-04 at 1 20 23 PM

**Comment by hacdias** [comment]
I addressed @juliaxbow's comments and removed the 'Cancel' button as it does not do anything different than 'Done' since it's already published.

https://user-images.githubusercontent.com/5447088/183389185-6d898e51-a98a-48b1-a84f-ef7783f00abc.mov

**Review by lidel — APPROVED** [review]
:ok_hand:

**Pull request merged**
