### PR TITLE
[WIP] chore: drop refs for files

### PR DESCRIPTION
**Pull request by fsdiogo**
This PR removes the files refs and uses the [`scrollToIndex`](https://github.com/bvaughn/react-virtualized/blob/master/docs/List.md#prop-types) prop to scroll to the desired row when using the keyboard navigation.

The `scrollToIndex` isn't working with WindowScroller, I've found [various](https://github.com/bvaughn/react-virtualized/issues/1226)  related [issues](https://github.com/bvaughn/react-virtualized/issues/1179).

Here are two examples demonstrating the problem:

✅ without WindowScroller: https://codesandbox.io/s/y23390y9yx
❌ with WindowScroller: https://codesandbox.io/s/1zjovmyy2j

When it gets fixed this PR should be unblocked!

### CODE REVIEW

**Comment by olizilla** [comment]
@fsdiogo it's totally ok to fork react-virtualised, apply the PR and rely on that if it's unclear when the PR will get merged.

**Comment by olizilla** [comment]
Any movement on this?

**Comment by fsdiogo** [comment]
Nope, everything is quiet.

Should I dig to find a solution and fork the repo if so?

**Comment by lidel** [comment]
Closing due to being stale + there has been many refactors of Files screen since 2019, so if this is still relevant needs a new PR anyway.

**Pull request closed without merging**
